# Generated by Django 4.2.13 on 2024-07-19 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
